---
name: DevilMode
version: 0.0.4
main: NhanAZ\DevilMode\Main
api: 5.0.0
author: NhanAZ
description: Players will not take damage when Devil Mode is enabled

commands:
  devil:
    description: "Will not take damage when Devil Mode is enabled"
    permission: devil.command

permissions:
  devil.command:
    default: op
    description: Allows use of /devil
...
