---
# Prefix of the message
Prefix: "&f[&eDevilMode&f]&r "

# Message sent to players when Devil Mode is enabled
EnableMsg: "&aDevil mode enabled!"

# Message sent to players when Devil Mode is disabled
DisableMsg: "&cDevil mode disabled!"
...
